org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.3.0
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=official
mapping_version=1.20.1

mod_id=matchmode
mod_name=Match Mode
mod_license=All Rights Reserved
mod_version=1.1.1
mod_group_id=com.matchmode
mod_authors=MatchMode
mod_description=Match mode: vote to start, darken, spectators, random presets, shrinking border. Server-side only.
