modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="matchmode"
version="${file.jarVersion}"
displayName="Match Mode"
authors="MatchMode"
displayTest="IGNORE_SERVER_VERSION"
description='''Match mode: vote to start, darken, spectators, random presets, shrinking border. Server-side only. Instant spectator on death with "ты 200" title.'''

[[dependencies.matchmode]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.matchmode]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"
